add timestamp to rpointer files
ESCOMP/MOSART pull request #105
Opened 2024-09-25 20:08 UTC by jedwards4b

Add timestamps to rpointer files, initialize curr date from driver and compare to what is in the restart files (instead of initializing from restart files).

2024-09-25 23:04 UTC, wwieder commented
I see this is no longer a draft. Are you ready for a review, Jim?

2024-09-26 01:15 UTC, jedwards4b commented
@wwieder Note that this is for mosart and is ready for review.  I will update the clm PR tomorrow.

2024-09-26 16:12 UTC, wwieder commented
Thanks for making the mosart PR.  What's the priority and timing of this across CESM?

2024-09-26 16:15 UTC, jedwards4b commented
I would like this to go into the cesm3_0_beta04 tag - probably within 30-45 days.

2024-10-03 19:15 UTC, jedwards4b commented
yes

2024-11-19 19:13 UTC, slevis-lmwg commented
@ekluzek when ready to merge this to master, remember that I merged to master the ChangeLog update without making a new tag.

#108

2024-12-21 00:00 UTC, ekluzek commented
Initial testing shows tests passing on Derecho and comparing exactly to the baseline as expected.

2024-12-23 09:57 UTC, ekluzek requested changes
Same comments as I had for the CTSM PR. I've done them there, will be easier to do the same here.

2024-12-23 09:57 UTC, ekluzek commented on src/cpl/nuopc/rof_comp_nuopc.F90
> -       ! Restart alarm
Add a comment about why the stop alarm should be first.

2024-12-23 09:57 UTC, ekluzek commented on src/riverroute/mosart_timemanager.F90
>           ! Print configuration summary to log file (stdout).
This doesn't need to be done, since it's already done in timemgr_init

2024-12-23 09:57 UTC, ekluzek commented on src/riverroute/mosart_timemanager.F90
Add comments about this no longer being something that is an either or with timemgr_init. Now, timemgr_init is always called. This also means timemgr_set should only be set with timemgr_init and here it's checked that it''s called.

2024-12-25 00:14 UTC, ekluzek approved these changes

2024-12-25 00:14 UTC, merged