addition of flux area correction factors
ESCOMP/MOSART pull request #40
Opened 2021-02-01 18:04 UTC by mvertens

This PR adds area flux correction factors as is done in CPL7.

2021-03-12 23:22 UTC, billsacks requested changes
Same comment/request as in https://github.com/ESCOMP/RTM/pull/24

2021-03-12 23:22 UTC, billsacks commented on src/cpl/nuopc/rof_import_export.F90
> +    real(r8), optional  , intent(in)    :: areacor(:)
As in https://github.com/ESCOMP/RTM/pull/24#discussion_r593500320 it seems problematic to have an optional argument appear before required arguments, here and in state_setexport. And as in https://github.com/ESCOMP/RTM/pull/24#discussion_r593500320, my preferred solution would be to have state_getimport directly use the module variable med2mod_areacor and state_setexport directly use mod2med_areacor.

2021-03-12 23:30 UTC, ekluzek approved these changes
I agree with @billsacks objection. areacor should be a required argument or used as a module variable. But, other than that it looks fine. Note, this includes some changes to OpenMP threads so we should ensure that's included in the testing (which it will for the CTSM tests).

2021-03-12 23:34 UTC, billsacks commented
Thanks @ekluzek . Note that the changes to threading are only in the nuopc cap, and threading with nuopc currently is *not* covered in our aux testing.

2021-03-12 23:58 UTC, billsacks commented
I discussed this with @mvertens . She pointed out that you don't always want to do the area correction – such as for states. We came up with an interface to these routines that I like better to handle this:
- Don't pass the area correction factors; instead, use the module variables (this way you don't accidentally mix up which area correction factor to use for the import/export)
- Add a new, _required_ argument: `do_area_correction`; the area correction will be applied if this is true. By making it required, we force someone adding a new field to consider whether it should be true or false for their new field.

2021-03-15 22:51 UTC, billsacks approved these changes

2021-03-16 19:52 UTC, billsacks commented
I have confirmed that my refactor did *not* change answers for the test `SMS_D_Ld5_Vnuopc.f10_f10_mg37.I2000Clm50BgcCrop.cheyenne_intel.mosart-default`, which I ran in the context of CESM's nuopc_dev branch. I will merge this shortly.

2021-03-16 22:26 UTC, merged